AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC, Subnet, and Route Table

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: MyVPC
      - Key: Environment
        Value: Sandbox
      - Key: CostCenter
        Value: WWC-A
      - Key: Owner
        Value: TeamA
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: MySubnet
      - Key: Environment
        Value: Sandbox
      - Key: CostCenter
        Value: WWC-A
      - Key: Owner
        Value: TeamA

  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: MyRouteTable
        - Key: Environment
          Value: Sandbox
        - Key: CostCenter
          Value: WWC-A
        - Key: Owner
          Value: TeamA

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MySubnet
      RouteTableId: !Ref MyRouteTable

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref MyVPC

  SubnetId:
    Description: Subnet ID
    Value: !Ref MySubnet

  RouteTableId:
    Description: Route Table ID
    Value: !Ref MyRouteTable